### PR TITLE
[DO NOT MERGE] coach-indicator: core token migration

### PR DESCRIPTION
**Pull request by Rajdeepc**
## Description

Core tokens update
New Coach Indicator Component

## Related issue(s)

- https://github.com/adobe/spectrum-css/pull/1992

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by Rajdeepc** [comment]
Awaiting some changes on the `--spectrum-coach-animation-indicator-ring` custom property before we can merge this in.

**Review by jenndiaz — APPROVED** [review]
CSS Looks good to me!

**Comment by Rajdeepc** [comment]
@Westbrook we have removed the local reference of the coach-indicator animation variable and moved it to custom-vars. 
Let me know if this looks good now! Thanks

**Comment by Westbrook** [comment]
can this be closed in exchange for #3639?

**Comment by Rajdeepc** [comment]
Yes. Closing this!

**Pull request closed without merging**
