### PR TITLE
Update to Storybook@7.0 via @web/storybook-builder

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- Adopt Storybook 7.0
  - unlocks federation
  - surfaces all Add-ons for consumption
  - speeds up builds/serving
- Move from `.storybook` to `storybook` to ensure publication to Netlify
- Include CSS storybook at dev time via federation
  - makes comparisons between the project easier than ever
  - exclude it at publication time

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://storybook--spectrum-web-components.netlify.app/storybook/)
    2. Experience the amazingness that is our storybook
-   [ ] _Test case 2_
    1. Switch to this branch
    2. `rm -rf node_modules`, the graph resolves funky otherwise
    3. `yarn`
    4. Run storybook locally, `yarn storybook`
    5. See that the CSS storybook is federated

## Screenshots (if appropriate)
image

## Types of changes
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

### CODE REVIEW

**Comment by beeduul** [comment]
ran `yarn` and `yarn storybook` on the storybook branch, commit [58c1188](https://github.com/adobe/spectrum-web-components/pull/3730/commits/58c11888c2dfa6998c6d6c697289f5b212e2046c), received the following error:

```
⬆️ [storybook] Service started
/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/highlight/lib/index.js:10
var _chalk = _interopRequireWildcard(require("chalk"), true);
                                     ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/chalk/source/index.js from /Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/highlight/lib/index.js not supported.
Instead change the require of /Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/chalk/source/index.js in /Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/highlight/lib/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/highlight/lib/index.js:10:38)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/code-frame/lib/index.js:8:18)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/traverse/lib/path/replacement.js:12:18)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/traverse/lib/path/index.js:17:28)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/traverse/lib/context.js:7:13)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/traverse/lib/traverse-node.js:7:16)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/node_modules/@babel/traverse/lib/index.js:29:21)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/csf-tools/dist/index.js:1:1889)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/telemetry/dist/index.js:12:4200)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/cli/dist/generate.js:11:4306)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/@storybook/cli/bin/index.js:26:1)
    at Object.<anonymous> (/Users/biddle/adobe/DIWI/spectrum-web-components/node_modules/storybook/index.js:3:1) {
  code: 'ERR_REQUIRE_ESM'
}
❌ [storybook] Service exited unexpectedly
```

**Comment by Westbrook** [comment]
Darn, I was hoping that was just me. It requires that you delete you `node_modules` or the install order will fail...I've an inkling that we'll likely need to move to NPM at some point to get up to a newer resolution model. NPM has all of the features we chose yarn for at this point, but that's a different conversation(s)...

**Comment by beeduul** [comment]
lgtm

**Review by beeduul — APPROVED** [review]
working well here (aside from the `node_modules` conflict issue)

**Pull request merged**
