### PR TITLE
refactor(field-group): use core tokens

### PR DESCRIPTION
**Pull request by lunarfusion**
## Description

This updates the Fieldgroup component to use core tokens

Uses beta release. Hold for full release.

## Related issue(s)

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by lunarfusion** [comment]
There are two failure patterns on field group which are expected given that the markup for field group has been updated to denote vertical and horizontal layouts. Correct styling will be applied when the markup is updated.

# Failure Pattern 1: Expected, web-components needs update to markup
Screen Shot 2022-09-17 at 10 03 30 AM

**Assessment:** Horizontal layout of field group items is shown in this failure with insufficient end margin on field group items. Margin-inline-end of each item should be `--spectrum-spacing-300` or 16px. This margin is applied through the class of `spectrum-FieldGroupInputLayout--horizontal` on the parent div of the field items so that it will only impact horizontally aligned fieldgroups.

# Failure Pattern 2: Expected, web-components needs update to markup
Screen Shot 2022-09-17 at 10 04 22 AM

**Assessment:** The fields are failing to align vertically due to the missing vertical layout class. A class of `spectrum-FieldGroupInputLayout--vertical` must be applied to the parent div of the field items so they will align flex column instead of flex row.

@Westbrook it looks like the markup needs to be updated so that each fieldgroup has the correct layout and styling for vertical and horizontal variations. Field group items need a wrapping div of `<div class="spectrum-FieldGroupInputLayout spectrum-FieldGroupInputLayout--vertical">` or `<div class="spectrum-FieldGroupInputLayout spectrum-FieldGroupInputLayout--horizontal">`. Please let me know if I can do anything to help with this.

**Comment by Westbrook** [comment]
Please take a look at https://github.com/adobe/spectrum-web-components/blob/main/packages/field-group/src/spectrum-config.js#L22-L33 where you should be able to update to `selector` values for the new classes names. You'll need to run `yarn` to ensure the new code is built before further testing and/or committing that update.

**Comment by lunarfusion** [comment]
> 



> Please take a look at https://github.com/adobe/spectrum-web-components/blob/main/packages/field-group/src/spectrum-config.js#L22-L33 where you should be able to update to `selector` values for the new classes names. You'll need to run `yarn` to ensure the new code is built before further testing and/or committing that update.

I can see now the error is on my end - I applied the horizontal and vertical modifier classes to a child div (.spectrum-FieldGroupInputLayout) when they should be applied to the parent div instead (.spectrum-FieldGroup). I'm going to update the component and come back and run this again.

**Comment by lunarfusion** [comment]
This is a revised assessment of the VRT failures in Fieldgroup. After the initial assessment, it was decided that Fieldgroup was intended to have a default layout featuring vertically aligned fields. This is a design change noted at https://spectrum.adobe.com/page/checkbox-group/ and https://spectrum.adobe.com/page/radio-group/ (screenshots included below).

# Failure Pattern 1: Expected due to design change
Screen Shot 2022-11-10 at 11 46 16 AM

All remaining failures are due to the default layout of fieldgroup having been changed from horizontal to vertical. The following are screenshots from spectrum.adobe.com specifying this change.
Screen Shot 2022-11-10 at 11 44 07 AM
Screen Shot 2022-11-10 at 11 44 20 AM

**Comment by pfulton** [comment]
This has been merged in the CSS repo, and the full release has been published: `@spectrum-css/fieldgroup@4.0.0`

**Pull request merged**
