### PR TITLE
performance: added memory tests in packages

### PR DESCRIPTION
**Pull request by Rajdeepc**
## Objective

The objective of this RFC is to propose a standardised approach for adding memory tests to each package in the component library using [Chrome's Performance API](https://developer.mozilla.org/en-US/docs/Web/API/Performance/measureUserAgentSpecificMemory), specifically the `measureUserAgentSpecificMemory()` method.

refs #3722

## Background

Memory leaks in web applications can lead to performance issues and degraded user experience. By adding memory tests to each package in the component library, we can proactively identify and fix potential memory leaks, ensuring the overall stability and performance of the library.

### Implementation of Memory Tests

1. The memory tests will be implemented using the `measureUserAgentSpecificMemory()` method from the Chrome Performance API.
2. The memory test for each package will consist of the following steps:
        - Create a test scenario that triggers the component's functionality.
        - Measure the memory usage before and after the test scenario.
        - Calculate the memory usage difference (DOM and JavaScript) to identify any memory leaks.

### Test Structure

1. Each memory test will be structured as a separate test case, following a standardised format.
2. The test case will include the following components:
        - Setup: Prepare the environment for the test.
        - Execution: Trigger the component's functionality.
        - Measurement: Measure the memory usage before and after the test.
        - Assertion: Verify that the memory usage difference is within an acceptable range.

### Test Helper Function

1. A test helper function named `usedHeapMB()` will be used to measure the memory usage.
2. The `usedHeapMB()` function will:
        - Call `measureUserAgentSpecificMemory()` to get the memory sample.
        - Parse the memory sample to extract the memory usage breakdown (DOM, JavaScript).
        - Return the memory usage breakdown in megabytes.

### Integration with Testing Framework

1. The memory tests will be integrated into the existing testing framework `@open-wc/testing` used for testing the SWC component library.
2. The memory tests will be executed as part of the automated test suite to ensure they are run regularly and consistently.

For more details on this experiment please go through this [RFC](https://paper.dropbox.com/doc/RFC-Adding-Memory-Tests-for-Component-Library-Packages--CMJMs9I58fIJUkqq87IGZ8KGAg-Q6ANtQLuEi5a8EkdGns1U)

## Related Issue:
Building on top of https://github.com/adobe/spectrum-web-components/pull/3721

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by Westbrook** [comment]
Great start here. Notice that the three files are now effectively the same. If there a path, similar to the [Lit Dev Mode test](https://github.com/adobe/spectrum-web-components/blob/main/test/testing-helpers.ts#L29-L54) that would allow for this boilerplate to be externalized?

**Comment by Westbrook** [comment]
Should the structure here look to interact with the abstraction listed as To Dos in https://github.com/adobe/spectrum-web-components/issues/1822?

**Comment by Rajdeepc** [comment]
> Great start here. Notice that the three files are now effectively the same. If there a path, similar to the [Lit Dev Mode test](https://github.com/adobe/spectrum-web-components/blob/main/test/testing-helpers.ts#L29-L54) that would allow for this boilerplate to be externalized?

Yes now I call it `testForMemoryLeaks`

**Review by Westbrook — COMMENTED** [review]
Please confirm that the helper is applicable to the grid and menu tests that were previously available.

**Comment by Rajdeepc** [comment]
> Please confirm that the helper is applicable to the grid and menu tests that were previously available.

Grid and Menu has been refactored to use the testing helper

**Review by Westbrook — APPROVED** [review]
LGTM! Catching up to `main` and then we can merge.

**Pull request merged**
