### PR TITLE
docs: added note about conventional commit reqs in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by DrewML**
## Description
Just adding a small note for `CONTRIBUTING.md` readers

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by Westbrook** [comment]
This is notes in README.md right now: https://github.com/adobe/spectrum-web-components#commitlint should we use that block? have both? move that block?

**Comment by DrewML** [comment]
> This is notes in README.md right now: adobe/spectrum-web-components#commitlint should we use that block? have both? move that block?

Whoops, totally missed it there!

When I opened my first PR, I had read through `CONTRIBUTING.md` based on the `Checklist` in the pull request template. I think either a note in the contributing docs _or_ a `Checklist` item would be good - probably don't need both, imho.

**Comment by Westbrook** [comment]
Agreed. Can you move that commitlint block from the README to the CONTRIBUTING, then it'll be in one place that can be referenced anytime the linter fails. Sound good?

**Comment by DrewML** [comment]
> Can you move that commitlint block from the README to the CONTRIBUTING, then it'll be in one place that can be referenced anytime the linter fails. Sound good?

Sounds good to me - pushed changes and updated commit message.

**Pull request merged**
