### PR TITLE
refactor(slider): use spectrum-tokens

### PR DESCRIPTION
**Pull request by pfulton**
## Description

Migrates Slider to the new tokens system. Using beta release. Hold for full release.

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by pfulton** [comment]
Spectrum CSS PR: https://github.com/adobe/spectrum-css/pull/1547

**Comment by mlogsdon18** [comment]
@Westbrook ok this one is ready for your review! I believe all of the VRT failures are due to some changes in spacing that are expected

**Comment by Westbrook** [comment]
Looks like that "label" and the "value" receive different styles which cause them not to share the same baseline. This is particularly evident in the "large" and "extra large" versions as can be exhibited in the CSS preview as well: https://pr-1696--spectrum-css.netlify.app/slider.html

image

**Comment by Westbrook** [comment]
This VRT points out a bug in Field Label where we are not applying a `--highcontrast-` custom property to https://github.com/adobe/spectrum-css/blob/main/components/fieldlabel/index.css#L160-L169

**Comment by Westbrook** [comment]
We use a handful of CSS Custom Properties internally:
https://github.com/adobe/spectrum-web-components/blob/slider-core-tokens/packages/slider/src/Slider.ts#L306
https://github.com/adobe/spectrum-web-components/blob/slider-core-tokens/packages/slider/src/Slider.ts#L420-L421
https://github.com/adobe/spectrum-web-components/blob/slider-core-tokens/packages/slider/src/HandleController.ts#L495-L496

Can you confirm that these align to the update names?

Also, if you would be so kind, would you mind fixing the typo in https://github.com/adobe/spectrum-web-components/blob/slider-core-tokens/packages/slider/src/HandleController.ts#L496 there's `-` missing in `var(-spectrum-slider-handle-default-border-color)` 🤦🏼

**Comment by mlogsdon18** [comment]
> Looks like that "label" and the "value" receive different styles which cause them not to share the same baseline. This is particularly evident in the "large" and "extra large" versions as can be exhibited in the CSS preview as well: https://pr-1696--spectrum-css.netlify.app/slider.html
> 
> image

@Westbrook This was checked and approved by PJ who recognized that this pixel or two difference was due to the line height of the label that's being applied. We have a token in place that moves the slider up some negative margin to account for that and design deemed that as acceptable. 
Screenshot 2023-05-16 at 10 18 22 AM

**Comment by mlogsdon18** [comment]
@Westbrook I went through and checked the custom CSS you all are implementing. Most of it is specific to SWC and wasn't in Spectrum CSS in the first place so we should be good there (your first two links). I did update the third link to reference the new variable coming in from Spectrum CSS just to eliminate an unneeded middle variable. 

I also went through the custom CSS file and removed some CSS that is no longer needed due to it being implemented in Specturm CSS. Specifically the `cursor: pointer` on the track and the border transition for the handle. 

I will put up a PR for the bug fix for Field Label in Spectrum CSS and hopefully we can get that in quickly!

**Comment by Westbrook** [comment]
@mlogsdon18 this is looking good! If we're able to get a stable release for this (and, hopefully, the Field Label) CSS then we'll be ready to clean up the VRTs, etc and merge this. Thanks for following up on everything and getting those ready to go. 🙇🏼‍♂️

**Comment by mlogsdon18** [comment]
@Westbrook WOO! I got some full releases and they have been updated in this PR
- Slider is now at 4.0.0
- Field Label is now at 7.0.0

**Review by Westbrook — APPROVED** [review]
@mlogsdon18 thanks for pushing this one through. Lots of great updates coming to our consumers here. Happy Friday!!

**Pull request merged**
