### PR TITLE
fix(overlay): overlay scroll in safari and firefox

### PR DESCRIPTION
**Pull request by caseyisonit**
## Description

Overlay needs a `display: flex` applied so that the children render correctly when they overflow the view height and can scroll. 

Resolves overflow and scrolling issues on Firefox and Safari for the following components:
- Overlay
- Combobox
- ActionMenu
- Menu
- Menu with Submenu
- Picker

## Related issue(s)

- https://jira.corp.adobe.com/browse/SWC-609

## Motivation and context

This allows users on Firefox and Safari to scroll and access all children in an overlay 

## How has this been tested?

-   [x] _Test case 1_
    1. In Firefox open each component listed above in storybook
    2. Make the viewport short
    3. Content within should scroll and the container should be within the margins
    
-   [ ] _Test case 2_
    1. In Safari open each component listed above in storybook
    2. Make the viewport short
    3. Content within should scroll and the container should be within the margins

-   [ ] _Test case 3_
    1. In Chrome open each component listed above in storybook
    2. Make the viewport short
    3. Content within should scroll and the container should be within the margins

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Types of changes

-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [X] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Review by Rajdeepc — CHANGES_REQUESTED** [review]
Amazing! Great catch! Would it be possible to create a reference test on the below test case to make sure the scroll also works in Webkit and Firefox engines?
Please refer to this [test](https://github.com/adobe/spectrum-web-components/blob/49f36cb92e6723d0089a1bc1988cfe5786a0f645/packages/overlay/test/overlay-trigger-extended.test.ts#L215)
You can use the below API to test for Webkit engines:
```js
import { isWebKit } from '@spectrum-web-components/shared';

```

**Review by Rajdeepc — DISMISSED** [review]

**Comment by AndreiBaicu26** [comment]
Hi @caseyisonit and @Rajdeepc   ! The flex css was specifically removed for this bug: 
 https://github.com/adobe/spectrum-web-components/pull/4902. Is there any other possible sollution ? 
 
Please see recordings attached.

**Comment by Rajdeepc** [comment]
> Hi @caseyisonit and @Rajdeepc ! The flex css was specifically removed for this bug: #4902. Is there any other possible sollution ?
> 
> Please see recordings attached.

Trying with something on this line to make sure we are not excluding a `sp-tooltip` binding
```css
:host(:not(:has(> sp-tooltip))) .dialog {
    display: flex;
}
```

**Comment by nikkimk** [comment]
https://caseyisonit-swc-609-overlay-scroll-bug--spectrum-web-components.netlify.app/storybook/iframe.html?args=&id=menu--default&viewMode=story in Safari is still cut off even with scroll.

**Comment by nikkimk** [comment]
> Hi @caseyisonit and @Rajdeepc ! The flex css was specifically removed for this bug:
https://github.com/adobe/spectrum-web-components/pull/4902. Is there any other possible sollution ?

We should probably have tests for both #4902 and for this fix to prevent reversions.

**Review by Rajdeepc — APPROVED** [review]
Approving this If you can add in a test for this that would be great but its not something that we should keep this blocked!

**Pull request merged**
