### PR TITLE
Avoid use of Node.isSameNode

### PR DESCRIPTION
**Pull request by matthias-ccri**
Replace `isSameNode` with `===`.

## Description

When the webcomponentsjs polyfills are applied, Node.isSameNode may fail if the argument is not a Node. This failure is not in the spec and is browser-specific. This change removes isSameNode and replaces it with direct comparison, which is equivalent.

## Related Issue

fixes #1369 1367
https://github.com/webcomponents/polyfills/issues/436

## Motivation and Context

Though spectrum-web-components does not officially support old browsers, this change may be a reasonable and low-impact change to make.

## How Has This Been Tested?

I ran `yarn test`.

## Screenshots (if appropriate):

N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by matthias-ccri** [comment]
I am in the process of securing permission for the CLA. Obviously this is a trivial change, but there's a process that I have to follow.

**Comment by matthias-ccri** [comment]
CLA signed

**Comment by Westbrook** [comment]
Hey @matthias-ccri, thanks so much for this!! I'm gonna take a little test drive tomorrow and run some of our perf suite, just to be sure, but hopefully we can get this into this weeks release for you 🤞🏼

**Comment by Westbrook** [comment]
Also, any work you've got pending here to warrant the `WIP` listing? Don't want to jump the gun on testing from this side.

**Comment by matthias-ccri** [comment]
Sorry, I've removed the WIP status, thanks!

**Review by Westbrook — APPROVED** [review]
Perf differences here are showing `unsure` by tooling and _look_ more like minute changes in our favor when not pretty balanced, so happy to move forward with this.

Thanks for the contribution!

**Pull request merged**
