### PR TITLE
fix(menu): enable numpad arrow and Enter keys

### LINKED ISSUE #3751: [Bug]: sp-menu does not honor Numpad keys for Arrow ⬆️ ⬇️  and Enter
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

Menu

### Expected behavior

Similar to how sp-menu supports navigating across with the help of keyboard arrow keys, it should also support Numpad arrow. Numpad Enter key also should work similar to the main Enter key.

### Actual behavior

Numpad keys are not handled at all.

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Chrome

### How can we reproduce this issue?

1. Go to [storybook menu item page](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/menu--single-select)
2. Click on the first menu item
3. Using keyboard having numpad, use the ⬆️ ⬇️ keys of the numpad region
4. Observe the active menu item doesn't change
5. Press enter key from the numpad section
6. Notice the menu item is not selected

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by nikkimk**
## Description

Handles `keydown` event by `event.key` instead of `event.code` so that numpad keys will work with menu.

## Related issue(s)

- fixes #3751 

## How has this been tested?

-   [ ] _Test case 1: No breaking changes for regular keys_
    1. Go [here](https://nikkimk-3751-bug-sp-menu-numpad-keys--spectrum-web-components.netlify.app/storybook/iframe.html?args=&id=menu--single-select&viewMode=story)
    2. Press <kbd>Tab</kbd>
    3. **_From the standard keypad,_** press <kbd>&darr;</kbd>
    4. **_From the standard keypad,_** press <kbd>Enter</kbd>
-   [ ] _Test case 2: Fix for Numpad keys_
    1. Go [here](https://nikkimk-3751-bug-sp-menu-numpad-keys--spectrum-web-components.netlify.app/storybook/iframe.html?args=&id=menu--single-select&viewMode=story)
    2. Press <kbd>Tab</kbd>
    3. **_From the Numpad,_** press <kbd>&darr;</kbd>
    4. **_From the Numpad,_** press <kbd>Enter</kbd>

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes. _(Note: There is no way to use `SendKeys` to test Numpad keys)_
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

**Comment by Rajdeepc** [comment]
@nikkimk Tests are making some noise! Can you please check and do the needful so that we can land this!

**Comment by blunteshwar** [comment]
Can we add some tests for this!

**Review by blunteshwar — CHANGES_REQUESTED** [review]
Can we add relevant tests for this

**Comment by nikkimk** [comment]
> * (Note: There is no way to use `SendKeys` to test Numpad keys)

@ blunteshwar any ideas on how to add tests for this given the above?

**Comment by blunteshwar** [comment]
> > * (Note: There is no way to use `SendKeys` to test Numpad keys)
> 
> @ blunteshwar any ideas on how to add tests for this given the above?

I think you can use SendKeys to send Numpad keys `await sendKeys({press: 'Enter',});` will work just fine.
I am attaching a videos as well where it is shown that replacing `Enter` with `NumpadEnter` has no effect on tests.

https://github.com/adobe/spectrum-web-components/assets/32033946/4aae6748-a3ad-44f0-81d2-8bf887822088

**Comment by nikkimk** [comment]
@blunteshwar thanks. I've added the update. We just won't be able to do Numpad arrow keys that way.

**Review by blunteshwar — APPROVED** [review]

**Review by Rajdeepc — APPROVED** [review]

**Pull request merged**
