### PR TITLE
refactor(tray): use spectrum tokens

### PR DESCRIPTION
**Pull request by yosevu**
## Description

See https://github.com/adobe/spectrum-css/pull/1535 and [this discussion](https://adobedesign.slack.com/archives/CS22GNRU2/p1667504713526569) for more context about this update.

### Changes

- `overlay-color` and `overlay-opacity` tokens are not included with Tray as they are the responsibility of Modal, which has not yet been migrated to use spectrum-tokens
- Tray is not positioned correctly in the the VRTs. This is due removing the  the containing element and the [`spectrum-Tray-wrapper`](https://github.com/adobe/spectrum-css/pull/1535/commits/7ceb3c6e05f4ff5343c7e4c41c6d91b0e8cf6da8). I believe this requires a similar containing element update in SWC, but I haven't looked at the implementation.

## Related issue(s)

-

## Motivation and context

Update Tray to use spectrum-tokens.

## How has this been tested?

- Tested design and open/close transitions in spectrum-css
- Looked at VRTs and the Documentation site, but I think we need to make some markup/style updates first to be able to test it correctly.

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by yosevu** [comment]
Hi @Westbrook, this is ready for a look. Please advise on if there are any issues with the changes as I am not familiar with how this component is used here.

**Comment by pfulton** [comment]
@Westbrook @yosevu it looks like we might be missing a `z-index` here, and one was provided before, albeit on the `.spectrum-Tray-wrapper`, which we've removed. Is `z-index` something you'd like CSS to provide, or does SWC manage that?

**Comment by yosevu** [comment]
> provided before

**Comment by yosevu** [comment]
> @Westbrook @yosevu it looks like we might be missing a `z-index` here, and one was [provided before](https://github.com/adobe/spectrum-css/blob/bca0cd5be2630ffd7b16fd10ab6005bddf5d4b58/components/tray/index.css#L30), albeit on the `.spectrum-Tray-wrapper`, which we've removed. Is `z-index` something you'd like CSS to provide, or does SWC manage that?

`spectrum-Modal`, which is used with `spectrum-Tray` has a `z-index: 2;` so I don't think another z-index is necessary to have on the containing element. I think the containing element should just be used for positioning. Does that make sense?

Screenshot 2022-11-17 at 8.35.44 AM

**Comment by pfulton** [comment]
This is looking much better now @yosevu

**Comment by yosevu** [comment]
I found an edge case/potential issue:

The SWC example on the doc site uses a small, `size="s"`, Dialog, while spectrum-css uses `spectrum-Dialog--large`. This means that the content of the Tray [does not span 100% of the width of the tray in portrait orientation](https://github.com/adobe/spectrum-css/pull/1535/files#diff-efb7037002cccc54259937cdfceac0c08fcac21ff2bedb1db00eb22ff6682165R99), including on larger screens as in the example.

[Tray did not have a design requirement for max-width to be based on orientation before](https://github.com/adobe/spectrum-css/blob/main/components/tray/index.css#L36).

Would it make sense to change the Dialog width to large @Westbrook @pfulton?

Small Dialog:
Screenshot 2022-11-21 at 5 01 27 PM

Large Dialog:
Screenshot 2022-11-21 at 5 01 38 PM

**Comment by pfulton** [comment]
> I found an edge case/potential issue:
> 
> The SWC example on the doc site uses a small, `size="s"`, Dialog, while spectrum-css uses `spectrum-Dialog--large`. This means that the content of the Tray [does not span 100% of the width in portrait orientation](https://github.com/adobe/spectrum-css/pull/1535/files#diff-efb7037002cccc54259937cdfceac0c08fcac21ff2bedb1db00eb22ff6682165R99), including on larger screens as in the example.
> 
> Tray did not have a design requirement for [max-width to be based on orientation before](https://github.com/adobe/spectrum-css/blob/main/components/tray/index.css#L36).
> 
> Would it make sense to change the Dialog width to large @Westbrook @pfulton?
> 

I'm not sure. What do you think @Westbrook?

**Comment by pfulton** [comment]
@Westbrook and I had a [Slack discussion](https://adobedesign.slack.com/archives/CS22GNRU2/p1670452759302199) about the Dialog width.

For this specific instance, the code here is for demo purposes, so it can be changed to accommodate whatever sizing we'd like to demonstrate.

However, there would likely be some benefits to using custom properties to allow for content flexibility within dialogs, and design indicated in the aforementioned Slack conversation that the content should grow/shrink in coordination with the container. We can handle that work when we migrate the Dialog component, and [I've made a note of this in the Jira ticket](https://jira.corp.adobe.com/browse/CSS-148) for that work.

I think we're good to move forward with merging this on the CSS side now.

**Comment by pfulton** [comment]
I merged the CSS PR and graduated the release. The tokens package also saw a version bump as a result of an addition there.

Here are the relevant releases:

```
- @spectrum-css/tray@2.0.0
- @spectrum-css/tokens@6.0.0
```

**Review by Westbrook — APPROVED** [review]
Looking good here. Sorry it took so long to get this wrapped!

**Pull request merged**
