### PR TITLE
refactor(link): use core tokens

### PR DESCRIPTION
**Pull request by yosevu**
### Updated Variant Examples

The main changes relate to the variant examples on the documentation site. 

- Remove T-Shirt Sizes
- Remove Over Background
- Remove Over Background - Quiet
- Add Static White
- Add Static White - Quiet
- Add Static Black
- Add Static Black - Quiet

## Related issue(s)

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by yosevu** [comment]
Hi @pfulton and @Westbrook, all differences that I have found are related to the variant examples. Should I try to update these?

- Remove T-Shirt Sizes
- Remove Over Background
- Remove Over Background - Quiet
- Add Static White
- Add Static White - Quiet
- Add Static Black
- Add Static Black - Quiet

**Comment by Westbrook** [comment]
Are t-shirt sizes for this patterns really being removed?

**Comment by Westbrook** [comment]
I'd like to add `static="white/black"` as we'll be changing the implementation of this across elements as part of the Core Tokens breaks, which means the available implementations are not worth repeating.

**Comment by pfulton** [comment]
> Are t-shirt sizes for this patterns really being removed?

@Westbrook yes, that's correct. After double-checking with design, they said "links should be whichever size the text is defined as"

**Review by pfulton — APPROVED** [review]

**Pull request merged**
