### PR TITLE
fix(textfield): add 'u' flag to keep consistency with native input el…

### LINKED ISSUE #1388: Add 'u' flag to be consistent with  "pattern" attribute of <input> element
https://github.com/adobe/spectrum-web-components/blob/8acfee43ce3be5d4a6da4cf1179d3400bca77968/packages/textfield/src/Textfield.ts#L231

see: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern

### PR DESCRIPTION
**Pull request by OpportunityLiu**
…ement

## Description

1. Add 'u' flag for both `"pattern"` and `"allowedKeys"`
2. Add boundary-type assertions (`^` and `$`) for pattern testing
3. Add related tests
4. Add `pathToFileURL` for css generation script, see https://github.com/nodejs/node/issues/34765

## Related Issue

fixes #1388 

## Motivation and Context

This change updates the behavior of multiline textfield pattern, to be consistant with native `input` element.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by OpportunityLiu** [comment]
The scripts still not working on Windows, so I'm testing with CI.

image

**Comment by Westbrook** [comment]
Thanks for the contribution! This looks great and I'm very happy to see the exhaustive testing on this 🚀 

Sorry, you're having trouble building in Windows. Would you be able to confirm whether updating the `package.json` at line 17 with the following supports building in that environment?

```
"build": "yarn build:css && tsc --build ./packages/*/tsconfig.json && tsc --build ./projects/story-decorator/tsconfig.json && tsc --build ./projects/vrt-compare/tsconfig.json",   
```

If not, we can find a path toward testing this more rigorously on our end, but I'd love it if this cleared up the situation.

**Comment by OpportunityLiu** [comment]
> Thanks for the contribution! This looks great and I'm very happy to see the exhaustive testing on this 🚀
> 
> Sorry, you're having trouble building in Windows. Would you be able to confirm whether updating the `package.json` at line 17 with the following supports building in that environment?
> 
> ```
> "build": "yarn build:css && tsc --build ./packages/*/tsconfig.json && tsc --build ./projects/story-decorator/tsconfig.json && tsc --build ./projects/vrt-compare/tsconfig.json",   
> ```
> 
> If not, we can find a path toward testing this more rigorously on our end, but I'd love it if this cleared up the situation.

Not working. It is the responsibility of application to explain glob patterns, not the shell, as in *nix.

**Review by Westbrook — APPROVED** [review]
LGTM.

Thanks for the contribution. We'll work on trying to get things working in Windows as per #909 but it may be a while.

**Pull request merged**
