### PR TITLE
fix(tabs): error on click - undefined tab target

### LINKED ISSUE #2000: [Bug]: sp-tabs error on click
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-tabs

### Expected behavior

A click inside sp-tabs but NOT on a sp-tab should not throw

### Actual behavior

Throws error because sp-tab target is undefined

### Screenshots

_No response_

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

1. Go to https://opensource.adobe.com/spectrum-web-components/components/tabs/
2. Click inside sp-tabs but NOT on a sp-tab
3. Check console
5. See error

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by sorinsarca**
## Description

A click inside sp-tabs throws if outside of a sp-tab.

## Related issue(s)

- fixes #2000 

## Motivation and context

Bugfix

## How has this been tested?

Manually

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Review by Westbrook — COMMENTED** [review]
Happy New Year! Thanks for the submission. Happy to get this into the library ASAP. To support that, would you be able to add a test for this? 🙏🏼

**Comment by sorinsarca** [comment]
Happy New Year!
To be honest, I don't know how to add a test in this case, mostly due to this:

> Warning: Exceptions thrown by event handlers are reported as uncaught exceptions. The event handlers run on a nested callstack; they block the caller until they complete, but exceptions do not propagate to the caller.

https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/dispatchEvent


Here is a test example

```ts
it('should not throw on click', async () => {
    const tabs = await createTabs();
    const tabList = (tabs.shadowRoot as ShadowRoot).querySelector('#list') as HTMLDivElement;

    expect(() => {
        // dispatchEvent() doesn't propagate the exception
        // same story with .click()
        tabList.dispatchEvent(new MouseEvent('click'));
    }).to.not.throw();
});
```

**Comment by Westbrook** [comment]
Your example test fails appropriately. How's it looking post the fix? There are certainly more complex recreations we could discuss (e.g. leveraging `sendMouse` or similar for a real pointer interaction), but if that works on both sides of the test, I'd be happy to approve.

**Comment by sorinsarca** [comment]
The problem is that it also fails if you replace `.to.not.throw()` with `.to.throw()`

After the fix there is no exception thrown, so the test passes - but it has zero value because it doesn't really test anything.
Maybe the testing framework provides some tools to "catch" errors thrown by event listeners, but I'm not aware of any.

**Comment by Westbrook** [comment]
Why would you want to use `expect().to.throw()`? It shouldn't throw, right?

The fact that the test fails in the old code and passes (presumably) with the new code, is the clarity that I think we want here while also adding coverage to see regressions if they were to arise.

Conversely, I could see this change being applied differently. If the `@click=${this.onClick}` binding were moved down from the `div` wrapper and down to the `slot` we should be able to get the same functionality without being able to trigger it on the "tab list" element, which would prevent the need to test it. Would need to confirm that the fix works as expected, but it would not require a test if it did indeed work.

**Comment by sorinsarca** [comment]
I've added the proposed test.
Too bad the testing framework doesn't have something to handle these cases.

**Review by Westbrook — APPROVED** [review]
LGTM! Thanks for catching this and putting up with the less than optimal test case to ensure it doesn't come up again. 🙏🏼

**Pull request merged**
