### PR TITLE
refactor(tooltip): migrate core tokens

### PR DESCRIPTION
**Pull request by lunarfusion**
## Description

This updates the Tooltip component to use core tokens

Uses beta release. Hold for full release.

## Related issue(s)

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by lunarfusion** [comment]
# VRT Failure Assessment

I've revised the tip placements for all 22 tooltip positions. Tip placement is now achieved with left/right/top/bottom positioning and the tip is centered in top/bottom/left/right/start/end positions with a transform. No margins are used for tip placement. The default tip position is for top tooltip and it is positioned with the following:

```
top: 100%;
left: 50%;
transform: translateX(-50%);
```

Here are the 22 positions as they appear in spectrum-css in LTR and RTL:

196512659-e5376264-bcae-4dac-98da-37005efe3e5f 4 34 31 PM
196512835-c6437dae-4193-4563-bf80-2f7fdd34e29d

**SWC Is currently showing the tip as off-center:**
Screen Shot 2022-12-02 at 4 23 32 PM

However, when I spin this up locally, the 4 positions represented here look correct:

Screen Shot 2022-12-02 at 4 48 48 PM

SWC does probably need to be updated to include all 22 tip positions. However, I am flummoxed as to why the VRTs are still showing the default tip position as off-center. @Westbrook any thoughts?

**Comment by Westbrook** [comment]
Currently, all of the "managed" Tooltip _tips_ seem to be off, just the width/height of the tip. On Monday I'll put in a commit that handles that in SWC and we can discuss whether that's the correct path or we want to find something in CSS to help centralize the delivery.

**Comment by lunarfusion** [comment]
# Assessment of VRT Failures

## Summary of Changes Expected to Impact VRTs

Tooltip's neutral background has changed. It is noticably lighter on all themes except Express light/lightest, in which it is darker (rgb(34, 34, 34).

Tooltip space to source has increased from 3px to 4/5px (medium/large).

## Failure Pattern 1: Expected

Failure expected due to background color change.

Screen Shot 2022-12-05 at 3 52 01 PM

## Failure Pattern 2: Expected

The position of Tooltip has shifted to 4px/5px from source, resulting in a lower position of the Tooltip relative to the previous iteration.

Screen Shot 2022-12-05 at 4 00 59 PM


## Failure Pattern: Unexpected

WHCM failure due to tip color overrides being incorrectly applied. Correction to follow.

Screen Shot 2022-12-05 at 3 48 29 PM

**Comment by pfulton** [comment]
This has been merged in CSS and the release was graduated out of beta. The full release version is `@spectrum-css/tooltip@4.0.0`

**Review by Westbrook — COMMENTED** [review]
Thanks @lunarfusion! Ready to go on this one. 🥳

**Review by Westbrook — APPROVED** [review]

**Pull request merged**
