### PR TITLE
chore(picker): fixed dev warning and test

### PR DESCRIPTION
**Pull request by TarunAdobe**
## Description

Very minor updates to fix the broken dev warning and a test in Picker

## Related issue(s)

-

## Motivation and context

I love good code that works.

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [x] Did it pass in Desktop?
-   [x] Did it pass in Mobile?
-   [x] Did it pass in iPad?

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Review by blunteshwar — DISMISSED** [review]
Perfect 👍

**Review by blunteshwar — COMMENTED** [review]
Please rectify the failing chromium tests

**Comment by TarunAdobe** [comment]
> Please rectify the failing chromium tests

Those tests are failing in main too. I will rectify in a separate PR.

**Review by Rajdeepc — APPROVED** [review]

**Comment by Rajdeepc** [comment]
I am okay to merge this! We already know that this issue is coming from a missing direct dependency from CSS.

**Pull request merged**
