### PR TITLE
bugfix(swatch): updated mixed swatch documentation

### PR DESCRIPTION
**Pull request by Rajdeepc**
## Description

Updated swatch documentation for mixed

## Related issue(s)

- https://github.com/adobe/spectrum-web-components/issues/3298

## How has this been tested?

chrome, axe

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Review by najikahalsema — APPROVED** [review]

**Comment by Westbrook** [comment]
This looks good. To support consumers in leveraging this change more successfully (sometimes we're the consumers we need to support 🤣), should we at support for _removing_ `mixed-value` when `selects !== 'multiple'` in [this method](https://github.com/adobe/spectrum-web-components/blob/main/packages/swatch/src/SwatchGroup.ts#L174)?

Or should we add a Dev Mode warning about the use of `mixed-value` outside of a `selects=='multiple'` group?

Happy to have this addressed in a follow up issue, if that felt better.

**Comment by najikahalsema** [comment]
> This looks good. To support consumers in leveraging this change more successfully (sometimes we're the consumers we need to support 🤣), should we at support for _removing_ `mixed-value` when `selects !== 'multiple'` in [this method](https://github.com/adobe/spectrum-web-components/blob/main/packages/swatch/src/SwatchGroup.ts#L174)?
> 
> Or should we add a Dev Mode warning about the use of `mixed-value` outside of a `selects=='multiple'` group?
> 
> Happy to have this addressed in a follow up issue, if that felt better.

yeah, this definitely still requires follow up work. thanks for noting it, westbrook.

**Comment by Rajdeepc** [comment]
@najikahalsema Feel free to close this. I can create another follow up issue.

**Comment by Westbrook** [comment]
This is the correct change here. No need to wait on the extra work to get this in. Thanks for handling this and the follow up request. 🙏🏼

**Pull request merged**
