### PR TITLE
Add Edge 79+ to supported browsers in README.md

### PR DESCRIPTION
**Pull request by DrewML**
🎉

## Description

Edgium!

## Motivation and Context
Advertise better browser support

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by DrewML** [comment]
> Should we add some hand wavy language about support with polyfills in previous releases/unlisted browsers at some point?

Good question! Think it depends: do we want the most adoption, or do we want to help push the needle on deprecation of IE11? 😀

**Comment by Westbrook** [comment]
Agree with killing IE11! Don't want to call it out directly in anyway. Used a version of this to test the commitlint integration in https://github.com/adobe/spectrum-web-components/pull/535 does that "explain support" without "supporting bad browser usage"?

**Comment by DrewML** [comment]
> There is one change that it would be great if you could help with. We use conventional commits, can you please update the commit message to something like docs: add Edge 79+ to supported browsers in README.md.

No problem! Pushed up a change

**Comment by DrewML** [comment]
Thanks @Westbrook! Y'all have done great work so far.

**Pull request merged**
