### PR TITLE
fix(tray): updated transition function to resolve correctly

### PR DESCRIPTION
**Pull request by Mohan-Pandit**
New relic captured log:
TypeError: this.resolveTransitionPromise is not a function at m.handleTrayTransitionend (https://illustrator.adobe.com/vendor-startup-spectrum-web-components.00819877d33dc34e0557.js:13863:898) at B.handleEvent (https://illustrator.adobe.com/vendor-startup-ui.c1f236f0113e70104d6c.js:2:170775) at HTMLDivElement.object (https://illustrator.adobe.com/id/urn:aaid:sc:AP:3628cca6-6665-4f66-840f-d1dc927ee425:1:10304) at HTMLDivElement.l (https://illustrator.adobe.com/id/urn:aaid:sc:AP:3628cca6-6665-4f66-840f-d1dc927ee425:1:33099)

Which suggests that `this.resolveTransitionPromise` is being access before initialized to a function.

Fix:
Dropping` ! ` in the line `private resolveTransitionPromise!: () => void;` and initialised default function and later it should get actual function.

## Related issue(s)

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by TarunAdobe** [comment]
@Mohan-Pandit CI seems to be angry after this change... Can you look into those failing tests?

**Comment by Mohan-Pandit** [comment]
@TarunAdobe  please take a look into this PR

**Review by Rajdeepc — APPROVED** [review]

**Comment by Mohan-Pandit** [comment]
@Rajdeepc  Shall I merge this PR?

**Comment by Rajdeepc** [comment]
> @Rajdeepc Shall I merge this PR?

We will merge this before our next release!

**Pull request merged**
