### PR TITLE
chore: use latest Spectrum CSS versions

### LINKED ISSUE #2229: [Bug]: WHCM doesn't render icons in text color
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

everything with an icon

### Expected behavior

Icons should be rendered in the same colour as their surrounding text

### Actual behavior

icons are rendered as the icon colour

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Chrome, Microsoft Edge

### How can we reproduce this issue?

1. Enable High Contrast mode (or emulation in chrome/edge)
2. Go to https://opensource.adobe.com/spectrum-web-components/components/accordion/
3. See icons are not in the text colour
4. Scroll to https://opensource.adobe.com/spectrum-css/accordion.html
5. See icons are correct in spectrum-css

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- update Windows High Contrast Mode support across the library by taking on the most recent Spectrum CSS versions

## Related issue(s)

- fixes #2229

## How has this been tested?

-   [ ] _Test case 1_
    1. Go [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/action-button-static-white-quiet--s)
    2. Also go [here](https://spectrum-css--spectrum-web-components.netlify.app/storybook/?path=/story/action-button-static-white-quiet--s)
    3. See which one did it better.
-   [ ] _Test case 2_
    1. Using Assistive Labs for Window High Contrast Mode
    2. Go [here](https://spectrum-css--spectrum-web-components.netlify.app/storybook/?path=/story/action-button-static-black-quiet--s) and all the other Action Button Stories
    3. See that they appear like: image
-   [ ] _Test case 3_
    1. Using Assistive Labs for Window High Contrast Mode
    2. Go [here](https://spectrum-css--spectrum-web-components.netlify.app/storybook/?path=/story/button-accent-fill--default) and all the other Button Stories w/ disabled buttons
    3. See that they appear like: image

## Types of changes
-   [x] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

### CODE REVIEW

**Review by najikahalsema — DISMISSED** [review]
lgtm!

**Comment by jnurthen** [comment]
Only found a few minor issues

1. There is no focus ring on black action buttons https://spectrum-css--spectrum-web-components.netlify.app/storybook/?path=/story/action-button-static-black--l
2. No focus indicator on Quiet Picker - https://spectrum-css--spectrum-web-components.netlify.app/storybook/?path=/story/picker--quiet
3. Disabled Status light doesn't have the disabled color - https://spectrum-css--spectrum-web-components.netlify.app/storybook/?path=/story/statuslight--disabled-true (very low priority - I think this might be dropped from spectrum)

**Comment by Westbrook** [comment]
@jnurthen are you seeing a focus ring here: https://opensource.adobe.com/spectrum-css/picker.html#quiet I am not, so we might not be able to get this from Spectrum CSS just yet. It _should_ be very close to what's going on with the Static Black Buttons, so if I'm able to interpolate, I will. Thanks for checking in on this! 🙇🏼‍♂️

**Comment by jnurthen** [comment]
> @jnurthen are you seeing a focus ring here: https://opensource.adobe.com/spectrum-css/picker.html#quiet I am not, so we might not be able to get this from Spectrum CSS just yet. It _should_ be very close to what's going on with the Static Black Buttons, so if I'm able to interpolate, I will. Thanks for checking in on this! 🙇🏼‍♂️

I'm not so I guess I missed that on spectrum-css. I'll file it there.

**Comment by Westbrook** [comment]
Update Static Black to have the right focus loupe color:

image

We'll wait of Spectrum CSS support for Picker and the Spectrum Design decisions on Status Light, so we should be good to go here.

**Pull request merged**
