### PR TITLE
feat(icon): use core tokens

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
Update Icons to Core Tokens

## How has this been tested?
-   [ ] _Test case 1_
    1. Go [here](https://icon-tokens--spectrum-web-components.netlify.app/storybook?path=/story/icon--medium)
    2. See it normalized to [here](https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/icon--medium).
-   [ ] _Test case 2_
    1. Review VRTs, if any changes are required to be accepted as part of the update.
        - Yes, the RTL Split Button is wonky, but that was true before this PR, too.

## Types of changes
-   [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jawinn** [comment]
It looks like the sizing difference is because of some of the custom CSS on the SWC side. I think most of this can now be removed: https://github.com/adobe/spectrum-web-components/blob/edac59003ecc1af8dc4aa91c00c9593e8792e63f/packages/icon/src/icon.css#L15-L49

I'm not aware of any XXS workflow size in design or tokens and that's not something we have in CSS, but if you need to keep that, it should be as simple as: 
```
:host([size='xxs']) {
    --mod-icon-size: var(--your-custom-xxs-size);
}
```
I did notice that xxl is missing its newly defined `--spectrum-workflow-icon-size-400` that was added to custom-vars as part of this PR. That's probably just because tokens would need its own release for that and a minimum version of that release set for Icon's dependencies.

### Custom properties update in [CSS Icon Migration PR](https://github.com/adobe/spectrum-css/pull/2347)

This migration has moved the sizing to custom properties, which should make things a lot easier for SWC to handle. I've updated that PR description with a bit more detail, but basically this is how the size is being set:
```
.spectrum-Icon {
  --spectrum-icon-inline-size: var(--mod-icon-inline-size, var(--mod-icon-size, var(--spectrum-icon-size)));
  --spectrum-icon-block-size: var(--mod-icon-block-size, var(--mod-icon-size, var(--spectrum-icon-size)));
  inline-size: var(--spectrum-icon-inline-size);
  block-size: var(--spectrum-icon-block-size);
 }
 ```
 The `--spectrum-icon-size` is defined for the various workflow size classes and individual UI icon size classes. E.g.: `.spectrum-Icon--sizeL { --spectrum-icon-size: var(--spectrum-workflow-icon-size-200); }`
And looking in the inspector, that CSS does seem to be coming over. It's just been overridden.

**Comment by jawinn** [comment]
@Westbrook New betas are available that include an XXS size token:

 - @spectrum-css/icon@6.0.0-beta.1
 - @spectrum-css/tokens@13.1.0-beta.1

**Comment by Westbrook** [comment]
@jawinn some tangentially related changes got snuck into this as I was growing my understanding of icons _generally_, but I think this looks like a winner! What are your thoughts on getting that one typo corrected in the upstread PM and promoting the work on the CSS side to stable?

**Comment by pfulton** [comment]
@Westbrook @jawinn here's the newly graduated release of the Icons! `@spectrum-css/icon@6.0.0`

**Review by najikahalsema — DISMISSED** [review]
lgtm! but what's with the config.yml conflict?

**Pull request merged**
