### PR TITLE
feat(tooltip): fixing the crash if tooltip parent is already removed from dom

### PR DESCRIPTION
**Pull request by anandpal-adobe**
## Related issue(s)

https://github.com/adobe/spectrum-web-components/issues/2359

-

## Motivation and context

This is needed if the parent view of tooltip is already removed, there was no check present which was causing the crash

## How has this been tested?

The issue was tested in venus app where crash was happening 

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Review by Westbrook — CHANGES_REQUESTED** [review]
Can you help us with a test case here? There's no clear situation where this should be needed, and may just be preventing functionality if there were.

**Comment by Westbrook** [comment]
We'd also prefer that you use a branch over a fork as outlined for you in Slack.

**Comment by ananpal** [comment]
@Westbrook the crash is happening in venus, with some button elements with elements; which are being created and removed just after that; as manageTooltip is being called asynchronously by the time manageTooltip run, parent element is already deleted. I am not sure how to add testcase for this.
I have added the check before adding or removing event from parent element only if parentElement is present. I dont see how it will prevent any functionality, rather it will just prevent application from crashing.
I am waiting for access request to be approved then I will create a new pr from branch.

**Comment by Westbrook** [comment]
Closing for lack of a test case. If you're able to supply one at a later date, we'd be happy to revisit this PR with you.

**Pull request closed without merging**
