### PR TITLE
Revert "fix(slider): allow handler to be focusable when slider is editable"

### PR DESCRIPTION
**Pull request by Rocss**
This reverts commit 23f8b8908a288f246f6330292b7ff090f931822a.

## Related issue(s)

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_

    1. Go here
    2. Do this

-   [ ] Did it pass in Desktop?
-   [ ] Did it pass in Mobile?
-   [ ] Did it pass in iPad?

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by Rajdeepc** [comment]
@Rocss Can you please add a little bit more context on this issue to check! Also would it be possible to write a test on this for a keyboard event trigger?

**Comment by Rocss** [comment]
> @Rocss Can you please add a little bit more context on this issue to check! Also would it be possible to write a test on this for a keyboard event trigger?

@Rajdeepc this is just a revert commit because I accidentally pushed to main. My PR will have unit tests on keyboard navigation, as it can be seen in the files changed.

**Review by caseyisonit — APPROVED** [review]

**Comment by caseyisonit** [comment]
@Rocss I have merged this in and you can now open a PR following our Contributing docs

**Comment by Rocss** [comment]
Thank you, @caseyisonit  and sorry for the inconvenience

**Comment by caseyisonit** [comment]
All good!! Glad it was caught :) On Nov 7, 2024, at 7:12 AM, Roxana Burduja ***@***.***> wrote:﻿
Thank you, @caseyisonit  and sorry for the inconvenience

**Pull request merged**
