### PR TITLE
fix(number-field): add support for modified stepping 

### PR DESCRIPTION
**Pull request by Westbrook**
## Description

Submitting to main the work that was previously reviewed in #1534 now that we've had an opportunity to send it through the full CI and preview site builds.

- added some `NaN` prevention in the wheel listener
- added a couple of tests

## Related Issue
refs #1528

## Motivation and Context
Easier user input collection

## How Has This Been Tested?
Unit tests

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by najikahalsema — COMMENTED** [review]
Looks good to me! Is there anything in the documentation for the number field that talks about using this step modifier, ie was it added in a previous commit/PR?

**Comment by Westbrook** [comment]
There isn't really. I'm also not sure we do a lot of "end user documentation" in other parts of the library, either.

Would "The `shift` key can be used to apply steps at `step-modifier` times their normal rate." be enough here, or would you see us benefiting from something more formal? Not really sure how to speak through a consuming developer to those users in a productive way.

**Comment by najikahalsema** [comment]
Yes, that seems sufficient to me!

**Review by najikahalsema — APPROVED** [review]

**Review by cuberoot — APPROVED** [review]
Approved. Looks good

**Pull request merged**
