### PR TITLE
chore: pr update from main branch

### PR DESCRIPTION
**Pull request by Rajdeepc**
# Automated Pull Request Update Workflow
This is an automated workflow to update pull requests (PRs) automatically. This document aims to provide information about the workflow's functionality, its benefits, and how contributors can make the most of it.

## Functionality
The automated PR update workflow is designed to keep open PRs up to date with the latest changes in the base branch. When changes are made to the base branch, eligible PRs will be automatically updated. This helps in the following ways:

1. **Reduced Merge Conflicts**: By updating PRs automatically, the likelihood of merge conflicts is minimised. When you're ready to merge your PR, it's more likely to merge smoothly.

2. **Early Feedback**: Automatic updates provide you with feedback on how your changes interact with the latest codebase. This helps you identify any issues early on and make necessary adjustments.

3. **Maintained Organization**: Outdated PRs can accumulate over time, making it difficult to manage and review them. The automated update workflow helps keep the repository organised by ensuring that PRs are always up to date.

# How to Benefit from the Workflow
To make the most of the automated PR update workflow, follow these guidelines:

1. **Submit Quality Pull Requests**: Ensure that your PRs are well-tested and meet the repository's guidelines before submission. This ensures that automated updates won't introduce unexpected issues.

2. **Review and Respond to Updates**: When your PR is updated automatically, you'll receive a notification. Take the time to review the changes and ensure they don't conflict with your work. If needed, make any necessary adjustments or respond to the updates through comments.

3. **Seek Support if Needed**: If you have any questions or need assistance regarding the automated update workflow, feel free to reach out for support. 

# Disabling Automated Updates
In some cases, you may want to disable the automated updates for your PR. If you need to do so, follow these steps:

Navigate to your PR's page.
1. In the conversation sidebar, locate the **Conversation tab**.
2. Scroll to the bottom of the page and find the Automated PR Update section.
3. Leave a comment mentioning that you would like to disable automated updates for your PR.
4. A maintainer will assist you with disabling the automated updates if it aligns with the repository's guidelines.

### CODE REVIEW

**Comment by Westbrook** [comment]
Can you share some more information around why you like this approach, what you think it will bring to the repo, and how we can inform/support contributors about its functionality so that it doesn't surprise them?

In particularly, I'd love to hear your thoughts on auto updating vs opt-in updating via: 
image

**Comment by Rajdeepc** [comment]
> Can you share some more information around why you like this approach, what you think it will bring to the repo, and how we can inform/support contributors about its functionality so that it doesn't surprise them?
> 
> In particularly, I'd love to hear your thoughts on auto updating vs opt-in updating via: image

@Westbrook I did my best to document best possible answers for you. Let me know if this helps or not.

Citations
[1] Forked from: [maxkomarychev/pr-updater-action](https://github.com/maxkomarychev/pr-updater-action)

**Comment by Rajdeepc** [comment]
@Westbrook If we dont think this is something we should add now, I can archive this PR for now. Let me know your thoughts!

**Comment by Rajdeepc** [comment]
> Would we expect this branch to be "up-to-date" at current thanks to the `in-review` label here?
> 
> Let me know if you feel this is ready to merge. Happy to merge it in and then do some live testing with it in our PRs, sometime the initial PR doesn't trigger things like actions, etc.. If that works out for us, we should then document this somewhere, Contributors docs or the PR template or at your suggestion.

Yes its ready to be moved in. We can do some follow up testing once merged. Thanks for reviewing this.

**Review by Westbrook — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
