### PR TITLE
refactor(toast): use core tokens

### PR DESCRIPTION
**Pull request by pfulton**
This adds the migrated-to-core-tokens Toast component.

## Related issue(s)

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by Westbrook** [comment]
Much bigger, namely in `medium`? The close button gets wonky there, too?

**Comment by pfulton** [comment]
> Much bigger, namely in medium? The close button gets wonky there, too?

Yep, looking funky. We'll investigate.

**Comment by pfulton** [comment]
@yosevu Mind taking a look at this?

**Comment by pfulton** [comment]
It looks like there's a `line-height` being applied here, but I'm unsure of where it's coming from. It's overriding the component's defined `line-height: var(--mod-toast-line-height, var(--spectrum-toast-line-height));` which would resolve to `1.3`.

Screen_Shot_2022-09-23_at_1_49_30_PM

Any thoughts on where this might be coming from, @Westbrook?

**Comment by Westbrook** [comment]
We apparently added it as part of the initial implementation of this: https://github.com/adobe/spectrum-web-components/blame/main/packages/toast/src/toast.css#L16

Please feel free to remove it if everything looks good to go with its removal!

**Comment by pfulton** [comment]
This is looking much better with the `line-height` adjustment. I've merged the CSS PR and graduated the beta. The newly released version is: `- @spectrum-css/toast@8.0.0`

**Pull request merged**
