### PR TITLE
fix(card): remove empty card state

### LINKED ISSUE #960: sp-card should hide the cover photo area if no slotted content is provided
### Expected Behaviour
Cards without previews are supported in the designs at https://spectrum.adobe.com/page/cards/ (easiest to see if you download the UI kit).

Ideally if you omit the `cover-photo` slot, it just doesn't show up.

### Actual Behaviour
In the "Empty" example at https://opensource.adobe.com/spectrum-web-components/components/card the cover photo section still takes up space.

### PR DESCRIPTION
**Pull request by najikahalsema**
## Description

* Remove `empty` card state from stories, visual regression testing, and documentation. 
* Include minor code changes to make sure empty cards aren't allowed 

## Related Issue

Fixes #960 

## Motivation and Context

Empty card slot feels redundant/silly to have, so it's best to get rid of it. 

## How Has This Been Tested?

* testing to see if empty card is possible with the code by removing empty state before removing it from documentation altogether
* looking at documentation/storybook to make sure empty card variant is not there

## Types of changes

- [ x ] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [ x ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [ x ] My code follows the code style of this project.
- [ x ] My change requires a change to the documentation.
- [ x ] I have updated the documentation accordingly.
- [ x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

### CODE REVIEW

**Review by adixon-adobe — CHANGES_REQUESTED** [review]
Can you repurpose the "Empty" example to instead just be an example that only has a heading & subheading? Maybe titled `No Preview Image`. With the other changes here it looks like that's rendering as I'd expect.

**Review by adixon-adobe — APPROVED** [review]
Awesome -- thanks!

**Comment by Westbrook** [comment]
Could you rebase `main`? Then CI and checks should clear and we can merge this in. Thanks!

**Review by Westbrook — APPROVED** [review]
Thanks for working through all the rough spots on this! :shipit:

**Pull request merged**
