### PR TITLE
feat(clear-button): migrate to core tokens

### PR DESCRIPTION
**Pull request by mlogsdon18**
## Description

Updates the Clear Button component to use core tokens.

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [x] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by mlogsdon18** [comment]
@Westbrook I'm fairly certain that the spacing issues here have to do with needing a new version of @spectrum-css/tokens. According to the `yarn.lock` this is currently using `^10.2.2` but it needs to be on at least version 11 in order to get the new in-field button tokens that are used by this component and a few others. I'm assuming you'll want to do that in a separate PR. Are we able to get that through?

**Comment by mlogsdon18** [comment]
@Westbrook I went ahead and updated the tokens version in this PR, so we can wait to get it merged until your PR to update that goes in but it is ready for your review. The Express VRTs are showing the button padding as off but the storybook is showing just fine so I think maybe there's a caching issue or something there?

**Comment by mlogsdon18** [comment]
@Westbrook This has been rebased with the new tokens version. It's still showing an issue with the Tag padding in the VRTs but it's not showing that in the Storybook. Do you have any idea why the tests would be showing something different?

**Comment by Westbrook** [comment]
@mlogsdon18 sorry for the long trek on this one. After spending a lot of time looking at other paths to understanding what's going on here, it seems that the failure you were seeing was out of date. The Express tests started to pass at some point, e.g. [here](https://app.circleci.com/pipelines/github/adobe/spectrum-web-components/17090/workflows/8de9828a-b394-48ee-987a-768330792b74/jobs/378297), which does not write a new VRT results, so [this one](https://cf6ec622d18400971f45e7cffad8d0fb--spectrum-web-components.netlify.app/review/) persisted, even though it was no longer the current commit hash (8d7572dce427a8575bff41aa4d780dd351d70fd2 vs 9d0138129307e7f693f719b109416c3c3835e0f8). 

Looks like we're ready for a stable CSS release and can get this merged in. Thanks for your patience!

**Comment by Westbrook** [comment]
Sorry, I messed up this branch thinking the 2.0 was related to this work. I'll patch it up when the real release goes out. 🙈

**Comment by mlogsdon18** [comment]
@Westbrook The release it out and Clear button is now 3.0.0. Do you want me to put up a commit for that or do you want to since you were saying there were some things you needed to fix?

**Comment by Westbrook** [comment]
The [3.0 release](https://unpkg.com/browse/@spectrum-css/clearbutton@3.0.0/) does not appear to be "build" (e.g. have the `dist` directory) the way the [2.0 release](https://unpkg.com/browse/@spectrum-css/clearbutton@2.0.0/) and prior have been.

**Comment by mlogsdon18** [comment]
> The [3.0 release](https://unpkg.com/browse/@spectrum-css/clearbutton@3.0.0/) does not appear to be "build" (e.g. have the `dist` directory) the way the [2.0 release](https://unpkg.com/browse/@spectrum-css/clearbutton@2.0.0/) and prior have been.



> The [3.0 release](https://unpkg.com/browse/@spectrum-css/clearbutton@3.0.0/) does not appear to be "build" (e.g. have the `dist` directory) the way the [2.0 release](https://unpkg.com/browse/@spectrum-css/clearbutton@2.0.0/) and prior have been.

Oh weird! Cassondra deprecated 3.0 on npm so could you use 4.0?

**Review by Westbrook — APPROVED** [review]
@mlogsdon18 sorry for the long cycle on this one, but it's time! Thanks for bringing this to the project 🙇🏼

**Pull request merged**
