### PR TITLE
feat(number-field): add number field pattern

### LINKED ISSUE #477: Add Spectrum CSS Number Field (Stepper) Pattern
### Expected Behaviour
https://opensource.adobe.com/spectrum-css/stepper.html should be available in the library.

### Actual Behaviour
Missing

### The future
image

### PR DESCRIPTION
**Pull request by Westbrook**
## Description
- correct `[disabled]` styling in `sp-action-button`
- organize `sp-textfield` for easier extension
- add `sp-number-field` element
  - Read the docs: https://westbrook-number-field--spectrum-web-components.netlify.app/components/number-field
  - Peruse the Storybook: https://westbrook-number-field--spectrum-web-components.netlify.app/storybook/?path=/story/number-field--default

To do:
- [ ] review issues with `max` in docs site
- [ ] ensure `min` and `max` usage with `step` is as documented

## Related Issue
fixes #477 

## Motivation and Context
Spectrum design system completeness

## How Has This Been Tested?
- units
- VRTs
- manually

## Screenshots (if appropriate):
image
image
image
image
image
image

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by najikahalsema — APPROVED** [review]
Awesome work!

**Review by najikahalsema — APPROVED** [review]

**Comment by Westbrook** [comment]
@najikahalsema I was having trouble with min/max in the documentation site, and while it seems like it was caused by my looking at the wrong build, I did realize there was a couple of realities around that I needed to manage that I hadn't. Please take another look and note the additional documentation around that handling.

@cuberoot I want to make sure you feel this aligns with what you're thinking you'll need on your end, either as _this_ change or a follow up PR.

**Comment by najikahalsema** [comment]
ugh , I approved it without checking the documentation for min/max like described. disregard my approval for now, but i'm sure it's fine.

**Review by cuberoot — APPROVED** [review]
Awesome work @Westbrook. This should solve my use cases and then some. Anything I hit in implementation of my features can be easily followed up with later.

**Review by cuberoot — DISMISSED** [review]

**Pull request merged**
