### PR TITLE
refactor(textfield): migrate spectrum tokens

### PR DESCRIPTION
**Pull request by lunarfusion**
## Description
This is a draft PR of the beta release of textfield. Hold for full release.

## Related issue(s)

-

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by lunarfusion** [comment]
@Westbrook something funky going on here. VRTs are showing exclusively results for Card:
Screen Shot 2022-12-14 at 5 41 50 PM

This is unexpected. I don't think textfield is implicated in card. Any idea what I got wrong here?

**Comment by Westbrook** [comment]
@lunarfusion that story _does_ have a Textfield as the headline for the Card, see: https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/card--slotted-heading

**Comment by lunarfusion** [comment]
# Assessment of VRT Failures - WIP

Corrections noted have been pushed to spectrum-css. Corrections showing up in SWC will be pending a beta bump in spectrum-css and a subsequent update to this PR.

## Failure Pattern 1 - Expected due to t-shirt sizes
Screenshot 2022-12-20 at 9 23 59 AM

**Card slotted heading** font size change may be due to the font size for input and placeholder lacking a default size when no t-shirt size is applied.

Card should ideally have a t-shirt size applied. However, to mitigate, I've applied the medium t-shirt size font size as a default to the input and placeholder text in a new commit on spectrum-css (update here pending beta bump).

## Failure Pattern 2 - Expected due to markup change

Screenshot 2022-12-20 at 9 27 26 AM

**Dialog wrapper form** appears to show textfield with no focus indicator. This is due to a markup change in textfield. The input now has an input wrapper div to facilitate the focus indicator:

```
        <div class="spectrum-Textfield-input-wrapper">
          <input id="textfield-sm" type="text" placeholder="Enter Password" name="field" value="" class="spectrum-Textfield-input" pattern=".{8,}" aria-describedby="helptext-1 character-count-1">
        </div>
```

## Failure Pattern 3 - Expected due to design change
**Field label stories:**
Screenshot 2022-12-20 at 9 30 19 AM

- Input placeholder text is no longer italic. This is a design change.
- Default border color for Spectrum is now rgb(144, 144, 144). This has changed from the previous default border color of rgb(177, 177, 177).

## Failure Pattern 4 - Expected due to markup change
**Icons UI Stories, Icons Workflow Stories**
Screenshot 2022-12-20 at 9 39 47 AM

**Search Stories**
Screenshot 2022-12-20 at 9 48 13 AM

**Textfield Stories**
Screenshot 2022-12-20 at 10 00 19 AM


Icon misalignment is likely due to the updated markup of textfield which adds an input wrapper within spectrum-textfield to facilitate alignment of child components and focus indicator. 

Note that no design specs have been provided for Search, which is being treated as a separate component migration.

## Failure Pattern 5 - Expected due to design change
**Number Field Stories** 
Screenshot 2022-12-20 at 9 44 22 AM
Screenshot 2022-12-20 at 9 44 30 AM

**Slider Stories**
Screenshot 2022-12-20 at 9 50 21 AM

failures appear to be a result of the design change which increased the inline-start padding within textfield.

## Failure Pattern 6 - Expected due to markup and design changes
**Text area** 
Icon misalignment likely due to markup changes.
Text area no longer has a vertical resize handle - this is a design change.
Invalid red color has changed.
Placeholder text is no longer italic.

"grows" variant is not supported in spectrum-css as it requires Javascript.
Screenshot 2022-12-20 at 9 54 51 AM

Quiet variant - text is no longer italic, focus indicator requires markup update.
Screenshot 2022-12-20 at 9 57 42 AM

Resize controls have been removed by design change.

Sized - width is set to a default of 240px which can be overridden.
Screenshot 2022-12-20 at 9 59 47 AM

**Comment by Westbrook** [comment]
@lunarfusion were you going to look into adding support for t-shirt sizes on the SWC size?

**Comment by lunarfusion** [comment]
# Assessment of VRT Failures - Revised

## Failure Pattern 1 - Text shifts up, expected due to design change
card-slotted-heading-line-height

**Card slotted heading**
Vertical shift of text is expected due to an increase in block padding


## Failure Pattern 2 - Focus border color, expected due to design change
dialog-focus-border

**Dialog**
Focus border color changed from blue to gray


## Failure Pattern 3 - Text style and color, expected due to design change
field-label

**Field label**
Placeholder text color changed, text no longer italic


## Failure Pattern 4 - Text shifts horizontally, expected due to design change
number-field-padding-start
Screenshot 2023-01-12 at 12 10 35 PM

**Number Field**
 Expected, padding-inline-start changed from 11px to 9px/12px/15px/15px (according to t-shirt size).

Screenshot 2023-01-12 at 12 12 13 PM

**Slider**
Text in textfield shifts up and right (or left in RTL) due to increased inline and block padding


## Failure Pattern 5 - Validation icon position, expected due to design and markup changes
textarea-icon-alignment

Screenshot 2023-01-12 at 1 43 00 PM

**Textarea and Textfield**
Icon position has moved vertically to top due to design change.
Icon block-end padding is not present because of markup change. Input now requires an input wrapper to ensure position of icons (as well as character count, helptext, and focus indicator) is correct. @Westbrook please confirm if this markup update dependency is copacetic.


## Failure Pattern 6 - Textarea Focused border, unexpected, requires SWC CSS removal
Screenshot 2023-01-12 at 12 43 37 PM

**Textarea Grows and Textarea Sized**
Blue border should not be present. Blue border visible on "grows" due to CSS overrides in packages/textfield/src/textfield.css, lines 111-125. I recommend these lines be removed.
@Westbrook - ok with you if I remove the CSS I am referring to here?


## Failure Pattern 6 - Textarea Sized Input Width - expected due to markup change
Screenshot 2023-01-12 at 12 53 11 PM

**Textarea Sized**
The width of the input is probably not correct due to the markup update which adds an input wrapper around the input. @Westbrook please confirm if this markup update dependency is copacetic.



# Assessment of VRT Failures - Undetermined, Please Advise 
@Westbrook 

## Failure Pattern 7 - Incorrect Icon position
Screenshot 2023-01-12 at 12 15 38 PM

**Search**
Icon position is incorrect. 

Cannot replicate the issue on spectrum-css, even when the markup is not updated to include the new input wrapper:
Screenshot 2023-01-12 at 12 29 44 PM


## Failure Pattern 8 - Elipses Absent - Unexpected
Screenshot 2023-01-12 at 1 46 31 PM

Screenshot 2023-01-12 at 1 46 37 PM

This is an error in my CSS, I am pushing a correction. 

## Failure Pattern 9 - Resize present on quiet textarea - Unexpected
Screenshot 2023-01-12 at 2 13 34 PM

This is an error in my CSS, I am pushing a correction. 

## Failure Pattern 10 - Textarea Grows Height
Screenshot 2023-01-12 at 12 50 25 PM

**Grows**
This may be out of scope for migration. Textarea inputs cannot resize to fit the content without the use of javascript. So this appears to be something that needs to be updated within SWC. 


## Failure Pattern 11 - Textarea Sized
Screenshot 2023-01-12 at 12 53 11 PM

**Sized**
The width of the input is probably not correct due to the markup update which adds an input wrapper around the input.

**Comment by lunarfusion** [comment]
WIP Assessment, pls hold....

# Assessment of VRT Failures - Revised v2

🪅 🥳 A new beta release, **4.0.0-beta.3,** includes refactoring of the textfield layout which removes the need to update the markup with an additional wrapping div around the input. Layout of the textfield and child components (field label, character count, help text) as well as the focus indicator is now achieved using CSS grid rather than requiring additional markup.

## Card Slotted Heading - Resolved

- **Expected:** Text shifts upward due to expected change; block-end padding has increased.
- **Unexpected, resolved**: Previous issue with the input not filling the correct horizontal space (evident by the bottom border falling short) has been corrected.

Screenshot 2023-01-24 at 5 16 19 PM

## Dialog Wrapper Form - Expected / Unexpected

- **Expected** - spacing shift is due to increased input padding
- **Expected** - focus border is now gray instead of blue, this is a design change
- **Unexpected:** focus indicator is missing, revision is coming version **4.0.0-beta.4**

Screenshot 2023-01-25 at 11 00 19 AM


## Field label - Expected

- **Expected** - Placeholder text is non-italic and darker in color, this is a design change
Screenshot 2023-01-25 at 11 04 51 AM

## Icon UI Elements

**Unexpected.** This one is tricky because spectrum-css treats search as a separate component which is being migrated later. I am working on creating defaults that resolve this icon misalignment without interfering with later Search migration work. A revision will will be needed in **4.0.0-beta.4** to correct this.

Screenshot 2023-01-25 at 11 07 18 AM

**Comment by lunarfusion** [comment]
To add Stepper to this migration work and overcome a merge conflict issue, we have opened a new PR for this migration work. 

New PR: https://github.com/adobe/spectrum-web-components/pull/2920

**Pull request closed without merging**
