### PR TITLE
docs: build a component inventory

### PR DESCRIPTION
**Pull request by hunterloftis**
## Description

Builds [a table](https://github.com/adobe/spectrum-web-components/blob/add-component-inventory/INVENTORY.md) of the currently-available components in Spectrum CSS alongside the currently-available components in SWC. Each cell links to the relevant component's documentation.

## Related issue(s)

fixes https://github.com/adobe/spectrum-web-components/issues/1765

(at least, it's a first pass at a component inventory - we may want to expose this on the static docs site too in some fashion)

## Motivation and context

It's hard to keep track of which components are available where because we have no automated way to track them (just a few outdated manual inventories). We field questions about this frequently.

## How has this been tested?

- check out the generated [table](https://github.com/adobe/spectrum-web-components/blob/add-component-inventory/INVENTORY.md)

## Screenshots (if appropriate)

image

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [X] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [X] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [X] My code follows the code style of this project.
-   [X] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [X] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [X] All new and existing tests passed.

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by Westbrook** [comment]
This looks awesome! Do you think it would be a big lift to get a `[link](...)` listing of some form in each column so this connects to both our docs and the CSS docs?

**Comment by hunterloftis** [comment]
@Westbrook I can hook that up - for formatting, are you thinking `✅  [Docs](url)`?

**Comment by hunterloftis** [comment]
@Westbrook linked!

**Review by Westbrook — APPROVED** [review]
Great to have this in the library!

**Pull request merged**
