### PR TITLE
fix(overlay): ensure smooth animation when opening modal overlays

### PR DESCRIPTION
**Pull request by Rocss**
## Description

Fixes an issue on Safari both iOS Mobile, Tablet and Web where the overlay would open right away, without an animation.
This reproduces on all overlays which use `type=modal`: Tray, Modal dialog, Picker.

Browser version used:
- Safari iOS Mobile 17.6.1
- Safari iOS Tablet 17.5.1
- Safari Web 17.5

**Tray before and after**

https://github.com/user-attachments/assets/5c18342c-e9fe-490d-af31-3b7d98c02aee

**Picker before**

https://github.com/user-attachments/assets/ad296df1-06ff-49b4-a24d-d8c2634022c7

**Picker after**

https://github.com/user-attachments/assets/b97d8ffe-1931-4f0e-b002-ebffbdd5c811

## Related issue(s)

- Fixes https://github.com/adobe/spectrum-web-components/issues/4819

## Motivation and context

See https://github.com/adobe/spectrum-web-components/issues/4819 for context

## How has this been tested?

-   [x] _Test case 1_
    1. On Safari iOS, Safari Tablet and Safari Web 
    2. Go to the Tray documentation: https://rocss-4819--spectrum-web-components.netlify.app/components/tray/
    3. Open and close the tray
    4. Both open and close animation should be smooth

-   [x] _Test case 2_
    1. On Safari iOS, Safari Tablet and Safari Web 
    2. Go to the Picker documentation: https://rocss-4819--spectrum-web-components.netlify.app/components/picker/
    3. Open and close the Picker
    4. Both open and close animation should be smooth

-   [x] _Test case 3_
    1. On Safari iOS, Safari Tablet and Safari Web 
    2. Go to the Dialog base documentation: https://rocss-4819--spectrum-web-components.netlify.app/components/dialog-base/
    3. Open and close the Dialog
    4. Both open and close animation should be smooth

-   [x] Did it pass in Desktop?
-   [x] Did it pass in Mobile?
-   [x] Did it pass in iPad?

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [x] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [x] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [x] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [x] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Review by rubencarvalho — APPROVED** [review]
Thank you so much for your research here! 🥇 
I'm so glad you found a solution! I tested on my side and all looks good!

**Review by rubencarvalho — CHANGES_REQUESTED** [review]
Ooops, unfortunately something seems to be breaking, select "RTL" and compare the links upon opening the overlay:

https://opensource.adobe.com/spectrum-web-components/storybook/index.html?path=/story/overlay-element--modal
https://rocss-4819--spectrum-web-components.netlify.app/storybook/?path=/story/overlay-element--modal

**Comment by Rocss** [comment]
I'm having a hard time reproducing the VRT failures, did you manage to reproduce this manually, @rubencarvalho?
Attaching a screenshot from the iOS:
IMG_7101

Are there any settings in the VRTs I should be aware of besides 'Reduce motion' and the RTL setting? 🤔

**Comment by Rocss** [comment]
LE: Oh wow nevermind, it reproduces on Chrome. And this was supposed to be the "good" browser!

**Review by rubencarvalho — APPROVED** [review]
Thank you again! I approved it, but let us wait until next week to merge this.

**Comment by Rocss** [comment]
@rubencarvalho is this due to the big 1.0 release?

**Review by TarunAdobe — APPROVED** [review]

**Review by Rajdeepc — APPROVED** [review]
Let's land it!

**Review by rubencarvalho — APPROVED** [review]

**Pull request merged**
