### PR TITLE
chore: process meter styles separately

### PR DESCRIPTION
**Pull request by TarunAdobe**
## Description

updated spectrum config to process meter styles correctly

## Related issue(s)

-

## How has this been tested?

-   [x] _Test case 1_
    1. Go [here](https://ttomar-meter--spectrum-web-components.netlify.app/storybook/?path=/story/meter-sizes--s)
    2. Click on all sizes

    1. Go here
    2. Do this

-   [x] Did it pass in Desktop?
-   [x] Did it pass in Mobile?
-   [x] Did it pass in iPad?

## Screenshots (if appropriate)
Size S

Screenshot 2024-10-21 at 2 31 43 PM

## Types of changes

-   [x] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [x] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [x] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by nikkimk** [comment]
@TarunAdobe can you add more detail in the `Description` and the `How has this been tested?` to provide context? Thanks!

**Review by rubencarvalho — CHANGES_REQUESTED** [review]
There is a small shift in the meter's top margin. Is it intended? Can we double check?
https://693ac22c5f422182eff1c58f317a2458--spectrum-web-components.netlify.app/review/#MeterStories/staticWhite.png

**Comment by Rajdeepc** [comment]
> There is a small shift in the meter's top margin. Is it intended? Can we double check? https://693ac22c5f422182eff1c58f317a2458--spectrum-web-components.netlify.app/review/#MeterStories/staticWhite.png

Compare from here: https://pr-2786--spectrum-css.netlify.app/?path=/story/components-meter--default

**Comment by TarunAdobe** [comment]
> There is a small shift in the meter's top margin. Is it intended? Can we double check? https://693ac22c5f422182eff1c58f317a2458--spectrum-web-components.netlify.app/review/#MeterStories/staticWhite.png

It is intended. Confirmed by css team.

**Review by Rajdeepc — APPROVED** [review]

**Review by rubencarvalho — APPROVED** [review]

**Pull request merged**
