### PR TITLE
chore: updated spectrum-css dependencies

### LINKED ISSUE #4084: [Bug]: tray has extra space on the sides in mobile
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

tray

### Expected behavior

In Spectrum CSS, [the tray in mobile goes edge to edge horizontally in the viewport](https://opensource.adobe.com/spectrum-css/preview/iframe.html?args=&id=components-tray--default&viewMode=story)

image

### Actual behavior

In Spectrum Web Components, [the tray has spacing on the sides of the tray](https://opensource.adobe.com/spectrum-web-components/storybook/iframe.html?args=&id=tray--default&viewMode=story)

image

### Screenshots

_No response_

### What browsers are you seeing the problem in?

Firefox, Chrome, Safari, Microsoft Edge

### How can we reproduce this issue?

1. Load [the tray story](https://opensource.adobe.com/spectrum-web-components/storybook/iframe.html?args=&id=tray--default&viewMode=story) in any browser. If on a desktop browser resize to a mobile size or switch to a mobile viewport in dev tools.
2. See horizontal spacing on either side of the tray component.

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by TarunAdobe**
## Description

updated the spectrum-css dependencies.

fixes #4084

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by Rajdeepc** [comment]
@TarunAdobe There are lint failure on some generated CSS files which needs to be pushed. Can you push it up and re-run the build?

**Comment by Westbrook** [comment]
These pending Buttons no longer show their text: https://1f63a3a8b3196261ee5c5581502af9a1--spectrum-web-components.netlify.app/review/

This _seems_ wrong: https://1f63a3a8b3196261ee5c5581502af9a1--spectrum-web-components.netlify.app/review/#ProgressCircleStories/inButton.png Maybe it's just that we previously applied `size="s"` to the Progress Circle, but not sure if we want to control for _if_ a users places a wrong sized Progress Circle in this location.

This change breaks Split Button delivery: https://1f63a3a8b3196261ee5c5581502af9a1--spectrum-web-components.netlify.app/review/#SplitButtonPrimaryMoreStories/m.png

**Review by Westbrook — CHANGES_REQUESTED** [review]
Need to work out the mismatches in the VRTs, we'll chat on this tomorrow.

**Comment by TarunAdobe** [comment]
@westbrook can you confirm if this is the expected tray or am i still missing something? (if yes then I'll update the golden image hash)

**Comment by Westbrook** [comment]
This seems right to me. Is there something specific about it has you unsure?

**Comment by TarunAdobe** [comment]
> This seems right to me. Is there something specific about it has you unsure?

Nope! I just wanted to double check before updating the golden image hash.

**Comment by Westbrook** [comment]
There are conflicts in this branch... 😢

**Comment by TarunAdobe** [comment]
> There are conflicts in this branch... 😢

If it's a perfect world, i'd have fixed the conflicts correctly! Did I mess something up?

**Review by Westbrook — APPROVED** [review]
Looks like we only end up changing the HCM VRTs with the latest review. LGTM!

First, I'll rebase this to the current `main`. If that passes, we can merge.

Then, I'll rebase the changes I mentioned to catch up Button and Split Button to this and hopefully I can get your review on that before you're off for the day.

**Pull request merged**
