### PR TITLE
refactor(progress-circle): use core tokens

### LINKED ISSUE #2519: [Bug]: sp-progress-circle over-background doesn't render properly within a button
### Code of conduct

- [X] I agree to follow this project's code of conduct.

### Impacted component(s)

sp-button, sp-progress-circle

### Expected behavior

You should be able to use a progress circle within the icon slot of a button.

### Actual behavior

In the dark theme, the background and progress both render white, like in this example:
https://studio.webcomponents.dev/edit/Ielqz00YFXN0rQVpIc2u

### Screenshots

color-override

### What browsers are you seeing the problem in?

_No response_

### How can we reproduce this issue?

Via this example: https://studio.webcomponents.dev/edit/Ielqz00YFXN0rQVpIc2u

### Sample code that illustrates the problem

_No response_

### Logs taken while reproducing problem

_No response_

### PR DESCRIPTION
**Pull request by pfulton**
This updates the ProgressCircle component to use core tokens

## Related issue(s)
- fixes #2519

## How has this been tested?

-   [ ] _Test case 1_
    1. Go here
    2. Do this
-   [ ] _Test case 2_
    1. Go here
    2. Do this

## Types of changes

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to change)
-   [ ] Chore (minor updates related to the tooling or maintenance of the repository, does not impact compiled assets)

## Checklist

-   [ ] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
-   [ ] My code follows the code style of this project.
-   [ ] If my change required a change to the documentation, I have updated the documentation in this pull request.
-   [ ] I have read the **[CONTRIBUTING](<(https://github.com/adobe/spectrum-web-components/blob/main/CONTRIBUTING.md)>)** document.
-   [ ] I have added tests to cover my changes.
-   [ ] All new and existing tests passed.
-   [ ] I have reviewed at the Accessibility Practices for this feature, see: [Aria Practices](https://www.w3.org/TR/wai-aria-practices/)

## Best practices

This repository uses conventional commit syntax for each commit message; note that the GitHub UI does not use this by default so be cautious when accepting suggested changes. Avoid the "Update branch" button on the pull request and opt instead for rebasing your branch against `main`.

### CODE REVIEW

**Comment by pfulton** [comment]
@lunarfusion Mind taking a look at this one?

**Comment by lunarfusion** [comment]
# Summary of Changes Impacting Failures
The blue of the progress circle changed in dark and darkest themes. Here is a visual swatch reference (from left to right, swatches are spectrum dark, spectrum darkest, and spectrum light/lightest):

spectrum progress circle color swatches

Track thickness has changed on large progress circles, medium theme, from 5px to 4px. This does not appear to be impacting the failures.

The gray track color is unchanged.

***
**The following are my assessments of the failures.**

# Failure pattern 1: Expected
classic-dark-large-ltr — 
classic-dark-large-rtl — 
express-dark-large-ltr — 
express-dark-large-rtl — 
classic-dark-medium-ltr — 
classic-dark-medium-rtl — 
express-dark-medium-ltr — 
express-dark-medium-rtl — 

**Assessment:** Failures expected due to blue color shift from rgb(84, 163, 246) to rgb(114, 183, 249)
Visual diff confirms (similar visual for all 8 failures).

dark-diff

# Failure pattern 2: Expected
classic-darkest-large-ltr — 
classic-darkest-large-rtl — 
express-darkest-large-ltr — 
express-darkest-large-rtl — 
classic-darkest-medium-ltr — 
classic-darkest-medium-rtl — 
express-darkest-medium-ltr — 
express-darkest-medium-rtl — 

**Assessment:** Failures expected due to blue color shift from rgb(64, 150, 243) to rgb(94, 170, 247)
Visual diff confirms (similar visual for all 8 failures).

darkest-diff

# Failure pattern 3: Unexpected
classic-light-medium-ltr — 
classic-light-medium-rtl — 
express-light-medium-ltr — 
express-light-medium-rtl — 
classic-light-large-ltr — 
classic-light-large-rtl — 
express-light-large-ltr — 
express-light-large-rtl — 
express-lightest-medium-ltr — 
express-lightest-medium-rtl — 
express-lightest-large-ltr — 
express-lightest-large-rtl — 

**Assessment:** Unexpected results. 
- This appears to be comparing the "Over Background" variant at https://opensource.adobe.com/spectrum-css/progresscircle.html with the default/standard appearance of progress circle. Should this be compared instead with the new "Static White" variant? If so, I'm not sure why this failure is only showing up on the light/lightest themes.
- If this test is meant to compare "Over Background" and "Static White", then the test will still fail due to a change in transparency from 20% opacity to 25% opacity.

These visuals appear consistent for all 12 of these failures.

Screen Shot 2022-09-02 at 3 22 39 PM

Screen Shot 2022-09-02 at 3 22 54 PM

# Failure pattern 4: Unexpected
classic-lightest-large-ltr — 
classic-lightest-large-rtl — 
classic-lightest-medium-ltr — 
classic-lightest-medium-rtl — 

**Assessment:** Failures NOT expected. Diff cannot be seen in the visuals - colors appear the same to me. The diff shows a stark difference, however. Not sure how to address this - please advise? Visual for reference:

classic-lightest-large

classic-lightest-large-diff

# Failure pattern 5: Expected, needs approval
hcm-visual — 

Failure expected, but please review this diff to make sure. Previously, the progress bar could not be read because the track and the fill were the same color. Visual:

Screen Shot 2022-09-02 at 2 11 02 PM

I changed the fill to a contrasting keyword so it can be seen:

Screen Shot 2022-09-02 at 2 11 11 PM

**Comment by lunarfusion** [comment]
@pfulton  To complete this PR, may I please follow up on these issues described in my previous comment above?

**Failure pattern 3: Unexpected**
Question: Is it safe to assume this failure is expected because it is comparing apples to oranges?

**Failure pattern 4: Unexpected**
Question: Is it safe to assume this is a false failure?

**Failure pattern 5: Expected, needs approval**
Question: Is my change to WHCM acceptable?

Thank you!

**Comment by pfulton** [comment]
> @pfulton To complete this PR, may I please follow up on these issues described in my previous comment above?
> 
> **Failure pattern 3: Unexpected** Question: Is it safe to assume this failure is expected because it is comparing apples to oranges?
> 
> **Failure pattern 4: Unexpected** Question: Is it safe to assume this is a false failure?
> 
> **Failure pattern 5: Expected, needs approval** Question: Is my change to WHCM acceptable?
> 
> Thank you!

* **Failure pattern 3:** Yeah, I think it's safe to assume that.
* **Failure pattern 4:** It looks like it might be a false failure - I wonder what happened on this one. Maybe @Westbrook can advise.
* **Failure pattern 5:** I think this looks OK to me. As to whether this is an acceptable a11y change: I'm definitely not the best judge there. We could ask accessibility in your original CSS PR to weigh in, though. I'll follow-up with you in Slack about this.

I think this is really close. I'll rebase this branch against the latest stuff in `main` and push up the changes.

**Comment by lunarfusion** [comment]
Failure Pattern 5 (WHCM) was reviewed with James Nurthen and a revision was made to match his recommendation.

**Comment by pfulton** [comment]
I've updated this to use the graduated version of the dependency. This is now ready for a full review.

**Comment by Westbrook** [comment]
Ship it!

**Pull request merged**
